### ISSUE TITLE
Cart horizontal acceleration

### ISSUE THREAD

**Issue by daniel-rutten-clickwise-limited** [colgreen/cartpole-physics#1]
Hi Colin,

Thanks so much for your code. I tried to understand the formulas behind it, but that made me nauseated :) This example has been a great help.

But (there's always a but, isn't there) I think I found a tiny little mistake in your horizontal calculation of the cart:

    xa = (g * ((m*sin_theta*cos_theta) + (m2*sin_theta2*cos_theta2))
         - (7f/3f) * (f +(m*l_hat*thetav_sqr*sin_theta) + (m2*l2_hat*thetav2_sqr*sin_theta2) - mu_c*xv)
         - (((mu_p*thetav*cos_theta)/l_hat) + ((mu_p*thetav2*cos_theta2)/l2_hat)))
         - / ((m*cos_theta_sqr) + (m2*cos_theta2_sqr) - (7/3)*M);`

At the end of this calculation you wrote (7/3), but I think you ment to write (7f/3f). It resulted in a tiny difference between you code and my Swift implementation of it.

I thought I'd mention it ...

- daniel

<img width="861" alt="Screen Shot 2021-05-25 at 16 25 47" src="https://user-images.githubusercontent.com/2120014/119439612-d9097b80-bd76-11eb-80f5-604bea6ee6f7.png">

**Comment by colgreen** [comment]
Well spotted! Thanks for reporting. Yes I see, 7/3 is performing integer arithmetic, which essentially truncates the fractional part of the result, so we get 2 instead of 2.33 recurring.

**Comment by daniel-rutten-clickwise-limited** [comment]
Easy to overlook ... glad I could help.
